FROM node:lts-alpine as build

WORKDIR /app

# Install dependencies
COPY Frontend/package.json package.json
RUN npm install --silent

# Copy Project files
COPY Frontend .

# Build App
RUN npm run build

#
# Add Nginx
#
FROM nginx:stable-alpine as production
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Expose Port
EXPOSE 80
EXPOSE 443

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]
